### ISSUE TITLE
ARM64 build issues

### ISSUE THREAD

**Issue by moodmosaic** [hirosystems/stacks-2-1-testing#60]
I'm trying to get this running under Windows ARM64 (for https://github.com/stacks-network/stacks-blockchain/issues/3845) but it looks like it's not supported? Or perhaps it's missing the C++ build tools?

```
Nikos@WIN-ARM64 MINGW64 ~/dev/projects/sbtc/stacks-e2e-testing (main)
$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠁ @hirosystems/stacks-devnet-js
error C:\Snapshot\dev\projects\sbtc\stacks-e2e-testing\node_modules\@hirosystems\stacks-devnet-js: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false || npm run build-release
Arguments:
Directory: C:\Snapshot\dev\projects\sbtc\stacks-e2e-testing\node_modules\@hirosystems\stacks-devnet-js
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@18.16.0 | win32 | x64
node-pre-gyp info check checked for "C:\Snapshot\dev\projects\sbtc\stacks-e2e-testing\node_modules\@hirosystems\stacks-devnet-js\native\index.node" (not found)
node-pre-gyp http GET https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-win32-x64-unknown.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-win32-x64-unknown.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-win32-x64-unknown.tar.gz
node-pre-gyp ERR! stack     at C:\Snapshot\dev\projects\sbtc\stacks-e2e-testing\node_modules\@mapbox\node-pre-gyp\lib\install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Windows_NT 10.0.22621
node-pre-gyp ERR! command "C:\\Snapshot\\bin\\node\\bin\\node.exe" "C:\\Snapshot\\dev\\projects\\sbtc\\stacks-e2e-testing\\node_modules\\@mapbox\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd C:\Snapshot\dev\projects\sbtc\stacks-e2e-testing\node_modules\@hirosystems\stacks-devnet-js
node-pre-gyp ERR! node -v v18.16.0
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-win32-x64-unknown.tar.gz

> @hirosystems/stacks-devnet-js@1.5.4 build-release
> npm run build -- --release


> @hirosystems/stacks-devnet-js@1.5.4 build
> tsc --build && cargo-cp-artifact -nc native/index.node -- cargo build --message-format=json-render-diagnostics --release

error TS5083: Cannot read file 'C:/Snapshot/dev/projects/sbtc/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js/tsconfig.json'.
```

**Comment by moodmosaic** [comment]
This happens also on Ubuntu ARM64, here's the output from `yarn install` after cloning the repo:

```
nikos@ubuntu-arm64:~/stacks-e2e-testing$ grep yarn README.md -m 1
yarn install
nikos@ubuntu-arm64:~/stacks-e2e-testing$ yarn install
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ @hirosystems/stacks-devnet-js
error /home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build=false || npm run build-release
Arguments:
Directory: /home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@1.0.10
node-pre-gyp info using node@18.17.1 | linux | arm64
node-pre-gyp info check checked for "/home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js/native/index.node" (not found)
node-pre-gyp http GET https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-linux-arm64-glibc.tar.gz
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-linux-arm64-glibc.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-linux-arm64-glibc.tar.gz
node-pre-gyp ERR! stack     at /home/nikos/stacks-e2e-testing/node_modules/@mapbox/node-pre-gyp/lib/install.js:67:15
node-pre-gyp ERR! stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
node-pre-gyp ERR! System Linux 5.15.0-56-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build=false"
node-pre-gyp ERR! cwd /home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js
node-pre-gyp ERR! node -v v18.17.1
node-pre-gyp ERR! node-pre-gyp -v v1.0.10
node-pre-gyp ERR! not ok
response status 404 Not Found on https://github.com/hirosystems/clarinet/releases/download/v1.5.4/stacks-devnet-js-linux-arm64-glibc.tar.gz

> @hirosystems/stacks-devnet-js@1.5.4 build-release
> npm run build -- --release


> @hirosystems/stacks-devnet-js@1.5.4 build
> tsc --build && cargo-cp-artifact -nc native/index.node -- cargo build --message-format=json-render-diagnostics --release

error TS5083: Cannot read file '/home/nikos/stacks-e2e-testing/node_modules/@hirosystems/stacks-devnet-js/tsconfig.json'.
npm notice
npm notice New minor version of npm available! 9.6.7 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice
```

**Comment by moodmosaic** [comment]
I can provide more info about both (Ubuntu and Windows) environments, if that helps. Just let me know.

**Comment by moodmosaic** [comment]
The gist is:

```bash
# ARM64 Windows
response status 404 Not Found on
  https://github.com/hirosystems/clarinet/releases/download/v1.5.4/
    stacks-devnet-js-win32-x64-unknown.tar.gz

# ARM64 Ubuntu
response status 404 Not Found on
  https://github.com/hirosystems/clarinet/releases/download/v1.5.4/
    stacks-devnet-js-linux-arm64-glibc.tar.gz
```
